{{- $fullName := include "devns.fullname" . -}}
{{- $fullName = printf "%s-%s" $fullName "wgapi-http" -}}

{{- if .Values.devns.wgapi.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}

kind: Ingress

metadata:
  name: {{ $fullName }}
  labels:
    {{- include "devns.labels" . | nindent 4 }}
  {{- with .Values.devns.wgapi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- with .Values.devns.wgapi }}
{{/*  {{- if .tls }}*/}}
{{/*  tls:*/}}
{{/*    {{- range .tls }}*/}}
{{/*    - hosts:*/}}
{{/*        {{- range .hosts }}*/}}
{{/*        - {{ . | quote }}*/}}
{{/*        {{- end }}*/}}
{{/*      secretName: {{ .secretName }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}
  rules:
    - host: {{ .hostname | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
{{- end }}