name: Go

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  release:
    types: [created]    

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm]
        module: [tlsapi, dnsserver, wgapi, wgclient]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      env:
        MODULE: ${{ matrix.module }}
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        VERSION: ${{ github.event.release.tag_name }}
      working-directory: ./${{ matrix.module }}
      run: go build -o ../build/$MODULE-$GOOS-$GOARCH-$VERSION
    - name: GH Release
      # You may pin to the exact commit or the version.
      # uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Gives the release a custom name. Defaults to tag name
        name: ${{ github.event.release.tag_name }}
        # Identify the release as a prerelease. Defaults to false
        prerelease: false
        # Newline-delimited list of path globs for asset files to upload
        files: "build/*"
